app-deployment:
  appName: video-manager-client
  image: nexus-docker-craigmiller160.ddns.net/video-manager-client:latest
  ports:
    - containerPort: 443
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 443
      scheme: HTTPS
secure_ingress:
  name: video-manager-ingress
  backendIsHttps: true
  hosts:
    - name: apps-craigmiller160.ddns.net
      services:
        - path: /(video-manager(/.*)?)
          serviceName: video-manager-client
          portNumber: 443