apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-manager-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-manager-client
  template:
    metadata:
      labels:
        app: video-manager-client
    spec:
      containers:
        - name: video-manager-client
          image: localhost:32000/video-manager-client:1.12.5
          ports:
            - containerPort: 443
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: video-manager-client-service
spec:
  type: ClusterIP
  selector:
    app: video-manager-client
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
